// Definition of the 3-dimensional Alfa curve
// (a Hilbert curve interpretation by Bos and Haverkort), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  { 2 3 -1 ]
    1
  { 3 1 -2 ]
    2
  [ 3 1 2 }
    -1
  { -2 -1 -3 ]
    3
  [ -2 -1 3 }
    1
  { -3 1 2 ]
    -2
  [ -3 1 -2 }
    -1
  [ -3 2 -1 }
>
