// Definition of the 4-dimensional Alfa curve
// (a Hilbert curve interpretation by Bos and Haverkort), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  { 3 2 4 -1 ]
    1
  { 3 4 1 -2 ]
    2
  [ 4 3 1 2 }
    -1
  { 4 -2 -1 -3 ]
    3
  [ 4 -2 -1 3 }
    1
  { 4 -3 1 2 ]
    -2
  [ -3 4 1 -2 }
    -1
  { -3 2 -1 -4 ]
    4
  [ -3 2 -1 4 }
    1
  { -3 -4 1 -2 ]
    2
  [ -4 -3 1 2 }
    -1
  { -4 -2 -1 3 ]
    -3
  [ -4 -2 -1 -3 }
    1
  { -4 3 1 2 ]
    -2
  [ -4 3 1 -2 }
    -1
  [ -4 2 3 -1 }
>
