// Definition of the 3-dimensional Base-Camp curve
// (a Hilbert curve interpretation by Haverkort), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 3 2 1 }
    1
  { 1 -2 -3 ]
    2
  [ 1 2 -3 }
    -1
  { -1 2 -3 ]
    3
  [ -1 2 3 }
    1
  { 1 2 3 ]
    -2
  [ 1 -2 3 }
    -1
  { -3 -2 1 ]
>
