// Definition of the 2-dimensional Base-Camp curve
// (a Hilbert curve interpretation by Haverkort), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 2 1 }
    1
  { 1 -2 ]
    2
  [ 1 2 }
    -1
  { -2 1 ]
>
