// Definition of the 4-dimensional Base-Camp curve
// (a Hilbert curve interpretation by Haverkort), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 4 2 3 1 }
    1
  { 1 -2 -3 -4 ]
    2
  [ 1 2 -3 -4 }
    -1
  { -1 2 -3 -4 ]
    3
  [ -1 2 3 -4 }
    1
  { 1 2 3 -4 ]
    -2
  [ 1 -2 3 -4 }
    -1
  { -1 -2 3 -4 ]
    4
  [ -1 -2 3 4 }
    1
  { 1 -2 3 4 ]
    2
  [ 1 2 3 4 }
    -1
  { -1 2 3 4 ]
    -3
  [ -1 2 -3 4 }
    1
  { 1 2 -3 4 ]
    -2
  [ 1 -2 -3 4 }
    -1
  { -4 -2 -3 1 ]
>
