// Definition of the 3-dimensional Beta curve
// (a facet-gated, hyperorthogonal Hilbert curve by Bos and Haverkort), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ -2 -1 3 }
    1
  [ -3 -2 1 }
    2
  { -3 2 1 ]
    -1
  [ 2 -3 -1 }
    3
  { 2 3 -1 ]
    1
  [ 3 2 1 }
    -2
  { 3 -2 1 ]
    -1
  { 3 -1 2 ]
>
