// Definition of the 3-dimensional Butz curve
// (a Hilbert curve interpretation by Butz), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  { 2 3 -1 ]
    1
  [ 3 1 2 }
    2
  { 3 1 -2 ]
    -1
  [ -1 -2 3 }
    3
  { -1 -2 -3 ]
    1
  [ -3 1 -2 }
    -2
  { -3 1 2 ]
    -1
  [ 2 -3 -1 }
>
