// Definition of the 2-dimensional Butz curve
// (a Hilbert curve interpretation by Butz), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  { 2 -1 ]
    1
  [ 1 2 }
    2
  { 1 -2 ]
    -1
  [ -2 -1 }
>
