// Definition of the 1-dimensional Coil curve
// (a generalization by Haverkort of Luxburg's Peano variation 1), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 }
    1
  [ 1 }
    1
  [ 1 }
>
