// Definition of the 4-dimensional Double-Gray-code traversal
// (consistent with Faloutsos and Samet), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 2 3 4 }
    1
  { -1 2 3 4 ]
    2
  [ -1 -2 3 4 }
    -1
  { 1 -2 3 4 ]
    3
  [ 1 -2 -3 4 }
    1
  { -1 -2 -3 4 ]
    -2
  [ -1 2 -3 4 }
    -1
  { 1 2 -3 4 ]
    4
  [ 1 2 -3 -4 }
    1
  { -1 2 -3 -4 ]
    2
  [ -1 -2 -3 -4 }
    -1
  { 1 -2 -3 -4 ]
    -3
  [ 1 -2 3 -4 }
    1
  { -1 -2 3 -4 ]
    -2
  [ -1 2 3 -4 }
    -1
  { 1 2 3 -4 ]
>
