// Definition of the 2-dimensional Gray-code traversal
// (as described by Samet), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 2 }
    1
  { 1 2 ]
    2
  [ 1 2 }
    -1
  { 1 2 ]
>
