// Definition of the 3-dimensional Gray-code traversal
// (as described by Samet), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 2 3 }
    1
  { 1 2 3 ]
    2
  [ 1 2 3 }
    -1
  { 1 2 3 ]
    3
  [ 1 2 3 }
    1
  { 1 2 3 ]
    -2
  [ 1 2 3 }
    -1
  { 1 2 3 ]
>
