// Definition of the 1-dimensional Half-Coil curve
// (a generalization by Haverkort of Luxburg's Peano variation 2), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 }
    1
  [ 1 }
    1
  [ 1 }
>
