// Definition of the 3-dimensional Half-Coil curve
// (a generalization by Haverkort of Luxburg's Peano variation 2), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 3 2 1 }
    1
  [ 1 -2 -3 }
    1
  [ 3 2 1 }
    2
  [ -1 2 -3 }
    -1
  [ 3 -2 -1 }
    -1
  [ -1 2 -3 }
    2
  [ 3 2 1 }
    1
  [ 1 -2 -3 }
    1
  [ 3 2 1 }
    3
  [ -1 -2 3 }
    -1
  [ -3 2 -1 }
    -1
  [ -1 -2 3 }
    -2
  [ -3 -2 1 }
    1
  [ 1 2 3 }
    1
  [ -3 -2 1 }
    -2
  [ -1 -2 3 }
    -1
  [ -3 2 -1 }
    -1
  [ -1 -2 3 }
    3
  [ 3 2 1 }
    1
  [ 1 -2 -3 }
    1
  [ 3 2 1 }
    2
  [ -1 2 -3 }
    -1
  [ 3 -2 -1 }
    -1
  [ -1 2 -3 }
    2
  [ 3 2 1 }
    1
  [ 1 -2 -3 }
    1
  [ 3 2 1 }
>
