// Definition of the 4-dimensional Hill-Z traversal
// (a Hill orthoscheme traversal designed by Haverkort), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 2 3 4 }
    1
  [ 1 2 3 4 }
   
  [ 2 1 3 4 }
    2
  [ 1 2 3 4 }
    -2
  [ 2 3 1 4 }
    2
  [ 1 3 2 4 }
   
  [ 3 1 2 4 }
    3
  [ 1 2 3 4 }
    -2 -3
  [ 2 3 4 1 }
    2
  [ 1 3 4 2 }
   
  [ 3 1 4 2 }
    3
  [ 1 2 4 3 }
    -3
  [ 3 4 1 2 }
    3
  [ 1 4 2 3 }
   
  [ 4 1 2 3 }
    4
  [ 1 2 3 4 }
>
