// Definition of the 3-dimensional Maehara-Reflected traversal
// (a Hill orthoscheme traversal designed by Haverkort, generalizing the Polya/Sierpinski curve, 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 2 3 }
    1
  { -1 2 3 ]
   
  [ 2 -1 3 }
    2
  { -2 -1 3 ]
    -2
  [ 2 3 -1 }
    2
  { -2 3 -1 ]
   
  [ 3 -2 -1 }
    3
  { -3 -2 -1 ]
>
