// Definition of the 5-dimensional Maehara-Reflected traversal
// (a Hill orthoscheme traversal designed by Haverkort, generalizing the Polya/Sierpinski curve, 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 2 3 4 5 }
    1
  { -1 2 3 4 5 ]
   
  [ 2 -1 3 4 5 }
    2
  { -2 -1 3 4 5 ]
    -2
  [ 2 3 -1 4 5 }
    2
  { -2 3 -1 4 5 ]
   
  [ 3 -2 -1 4 5 }
    3
  { -3 -2 -1 4 5 ]
    -2 -3
  [ 2 3 4 -1 5 }
    2
  { -2 3 4 -1 5 ]
   
  [ 3 -2 4 -1 5 }
    3
  { -3 -2 4 -1 5 ]
    -3
  [ 3 4 -2 -1 5 }
    3
  { -3 4 -2 -1 5 ]
   
  [ 4 -3 -2 -1 5 }
    4
  { -4 -3 -2 -1 5 ]
    -2 -3 -4
  [ 2 3 4 5 -1 }
    2
  { -2 3 4 5 -1 ]
   
  [ 3 -2 4 5 -1 }
    3
  { -3 -2 4 5 -1 ]
    -3
  [ 3 4 -2 5 -1 }
    3
  { -3 4 -2 5 -1 ]
   
  [ 4 -3 -2 5 -1 }
    4
  { -4 -3 -2 5 -1 ]
    -3 -4
  [ 3 4 5 -2 -1 }
    3
  { -3 4 5 -2 -1 ]
   
  [ 4 -3 5 -2 -1 }
    4
  { -4 -3 5 -2 -1 ]
    -4
  [ 4 5 -3 -2 -1 }
    4
  { -4 5 -3 -2 -1 ]
   
  [ 5 -4 -3 -2 -1 }
    5
  { -5 -4 -3 -2 -1 ]
>
