// Definition of the 2-dimensional Maehara-Reflected traversal
// (a Hill orthoscheme traversal designed by Haverkort, generalizing the Polya/Sierpinski curve, 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 2 }
    1
  { -1 2 ]
   
  [ 2 -1 }
    2
  { -2 -1 ]
>
