// Definition of the 3-dimensional Meurthe curve
// (a generalization of the curve by Haverkort and Van Walderveen), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 3 2 1 }
    1
  [ -3 -2 1 }
    1
  [ 1 3 2 }
    2
  [ -3 2 -1 }
    -1
  [ 3 -2 -1 }
    -1
  [ -1 -3 2 }
    2
  [ 2 3 1 }
    1
  [ -2 -3 1 }
    1
  [ 1 2 3 }
    3
  [ 3 -2 -1 }
    -1
  [ -3 2 -1 }
    -1
  [ -1 3 -2 }
    -2
  [ -3 -2 1 }
    1
  [ 3 2 1 }
    1
  [ 1 -3 -2 }
    -2
  [ -2 3 -1 }
    -1
  [ 2 -3 -1 }
    -1
  [ -1 -2 3 }
    3
  [ 3 2 1 }
    1
  [ -3 -2 1 }
    1
  [ 1 3 2 }
    2
  [ -3 2 -1 }
    -1
  [ 3 -2 -1 }
    -1
  [ -1 -3 2 }
    2
  [ 2 3 1 }
    1
  [ -2 -3 1 }
    1
  [ 1 2 3 }
>
