// Definition of the 2-dimensional Meurthe curve
// (a generalization of the curve by Haverkort and Van Walderveen), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 2 1 }
    1
  [ -2 1 }
    1
  [ 1 2 }
    2
  [ 2 -1 }
    -1
  [ -2 -1 }
    -1
  [ -1 2 }
    2
  [ 2 1 }
    1
  [ -2 1 }
    1
  [ 1 2 }
>
