// Definition of the 1-dimensional Meurthe curve
// (a generalization of the curve by Haverkort and Van Walderveen), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 }
    1
  [ 1 }
    1
  [ 1 }
>
