// Definition of the 2-dimensional Peano curve, 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 2 }
    1
  [ 1 -2 }
    1
  [ 1 2 }
    2
  [ -1 2 }
    -1
  [ -1 -2 }
    -1
  [ -1 2 }
    2
  [ 1 2 }
    1
  [ 1 -2 }
    1
  [ 1 2 }
>
