// Definition of the 2-dimensional U-order traversal
// (generalized from Schrack and Liu), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 2 }
    1
  [ 1 2 }
    2
  [ 1 2 }
    -1
  [ 1 2 }
>
