// Definition of the 3-dimensional U-order traversal
// (generalized from Schrack and Liu), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 2 3 }
    1
  [ 1 2 3 }
    2
  [ 1 2 3 }
    -1
  [ 1 2 3 }
    3
  [ 1 2 3 }
    1
  [ 1 2 3 }
    -2
  [ 1 2 3 }
    -1
  [ 1 2 3 }
>
