// Definition of the 4-dimensional U-order traversal
// (generalized from Schrack and Liu), 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 2 3 4 }
    1
  [ 1 2 3 4 }
    2
  [ 1 2 3 4 }
    -1
  [ 1 2 3 4 }
    3
  [ 1 2 3 4 }
    1
  [ 1 2 3 4 }
    -2
  [ 1 2 3 4 }
    -1
  [ 1 2 3 4 }
    4
  [ 1 2 3 4 }
    1
  [ 1 2 3 4 }
    2
  [ 1 2 3 4 }
    -1
  [ 1 2 3 4 }
    -3
  [ 1 2 3 4 }
    1
  [ 1 2 3 4 }
    -2
  [ 1 2 3 4 }
    -1
  [ 1 2 3 4 }
>
