// Definition of the 4-dimensional Morton/Z-order traversal, 
// generated by SpaceTravel 0.1 by Herman Haverkort.
<
  [ 1 2 3 4 }
    1
  [ 1 2 3 4 }
    -1 2
  [ 1 2 3 4 }
    1
  [ 1 2 3 4 }
    -1 -2 3
  [ 1 2 3 4 }
    1
  [ 1 2 3 4 }
    -1 2
  [ 1 2 3 4 }
    1
  [ 1 2 3 4 }
    -1 -2 -3 4
  [ 1 2 3 4 }
    1
  [ 1 2 3 4 }
    -1 2
  [ 1 2 3 4 }
    1
  [ 1 2 3 4 }
    -1 -2 3
  [ 1 2 3 4 }
    1
  [ 1 2 3 4 }
    -1 2
  [ 1 2 3 4 }
    1
  [ 1 2 3 4 }
>
